### ISSUE TITLE
Update docs for jib-gradle-plugin.

### ISSUE THREAD

**Issue by coollog** [google/jib#208]
- [x] Add `README.md` to `jib-gradle-plugin`. (#210)
- [x] Add `README.md` to `jib-maven-plugin`. (#219)
- [x] Change root `README.md` to be project description and link to each specific plugin's `README`. (#220)
- [x] Move FAQ to Wiki
